//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Basico.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class libros
    {
        [Display(Name = "#")]
        public int id { get; set; }
        [Display(Name = "Nombre Del Libro")]
        public string nombre { get; set; }
        [Display(Name = "Autor Del Libro")]
        public string autor { get; set; }
        [Display(Name = "Fecha De Lanzamiento")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
